# Generated by Django 3.0.8 on 2020-07-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='technology',
            field=models.CharField(default='Python', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='media'),
        ),
    ]
